configname: exp_config/kuma.yaml
out: result/looting/
path: data/looting/*
extension: ply
epochs: 100
trials: 50
norm: one_minus
single_method: [M, M+L1TD, M+TVN, M+TVN+L1TD]
double_method: []
feature_method: [--fourier, --siren]
lr: #log search
  - 1.e-5 # min
  - 1.e-2 # max
bs: # power of 2 search
  - 11 # 2048 # min
  - 14 # 16384 # max
scale: # power of 2 search
  - 0 # min
  - 10 # max
mapping_size: # power of 2 search
  - 7 # min
  - 11 # max
lambda_discrete: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_gradient_time: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_tvn: #log search
  - 1.e-5 # min
  - 1.e+1 # max
siren:
  hidden_num: [4, 6]
  hidden_dim: [7, 9] # power of 2 search
  do_skip: [1]
act: [tanh]
arch: [skip-5]
verbose: 0
