configname: exp_config/looting_home.yaml
out: result/home_looting
path: data/looting_activity/cambodia_1_named/*
extension: txt
epochs: 10
trials: 3
norm: "one_minus"
single_method: [M+L1TD+TVN] #, M+L1TG M , M+L1TD, , M+TVN
double_method: [] # [M, M+TVN]
feature_method: [--siren] # [, --siren, ""], --fourier, ""
lr: #log search
  - 1.e-5 # min
  - 1.e-1 # max
bs: # power of 2 search
  - 9 # 512 # min
  - 13 # 2048 # max
scale: # power of 2 search
  - 0 # min
  - 8 # max
mapping_size: # power of 2 search
  - 7 # min
  - 11 # max
lambda_discrete: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_gradient_time: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_tvn: #log search
  - 1.e-5 # min
  - 1.e+1 # max
siren:
  hidden_num: [1, 5]
  hidden_dim: [6, 10] # power of 2 search
  do_skip: [0, 1]
loss_tvn: [l1]
act: [tanh, relu]
arch: [default, Vlarge, skip-4, skip-5, skip-6]
verbose: 1
