configname: exp_config/paper_ablation.yaml
out: result/ablation
path: data/full_data/
gtpath: data/full_data/
extension: ply
epochs: 50
trials: 20
repetitions: 40
norm: one_minus
single_method: [M+L1TD, M+TVN]
feature_method: [--fourier, --siren]
lr: #log search
  - 1.e-5 # min
  - 1.e-2 # max
bs: # power of 2 search
  - 11 # 2048 # min
  - 14 # 16384 # max
scale: # power of 2 search
  - 0 # min
  - 10 # max
mapping_size: # power of 2 search
  - 7 # min
  - 11 # max
siren:
  hidden_num: [4, 6]
  hidden_dim: [7, 9] # power of 2 search
  do_skip: [1]
act: [tanh]
arch: [skip-5]
lambda: [0, 0.0001, 0.0002, 0.0005, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5]
verbose: 0
