configname: exp_config/paper.yaml
out: result/paper
path: data/full_data/
extension: ply
epochs: 10 #50
trials: 10 #50
norm: one_minus
single_method: [M, M+TD, M+TD+TVN, M+TVN]
double_method: [M, M+TVN]
feature_method: [--fourier, --siren, ""]
lr: #log search
  - 1.e-5 # min
  - 1.e-2 # max
bs: # power of 2 search
  - 11 # 2048 # min
  - 14 # 16384 # max
scale: # power of 2 search
  - 0 # min
  - 10 # max
mapping_size: # power of 2 search
  - 5 # min
  - 11 # max
lambda_td: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_tvn: #log search
  - 1.e-5 # min
  - 1.e+1 # max
siren:
  hidden_num: [2, 8]
  hidden_dim: [5, 10] # power of 2 search
  do_skip: [1]
act: [relu, tanh]
arch: [skip-ten-only] # [default, default-BN, default-L, skip-double, skip-L-double, skip-XL-double, skip-ten, skip-ten-only, skip-twenty]
verbose: 0
