configname: exp_config/paper.yaml
out: result/paper
path: data/full_data/
extension: ply
epochs: 50
trials: 50
norm: one_minus
single_method: [M+L1TD, M+L1TD+TVN, M+TVN]
double_method: [M+TVN]
fourier: [--fourier]
lr: #log search
  - 1.e-5 # min
  - 1.e-1 # max
wd: #log search
  - 1.e-5 # min
  - 1.e+1 # max
bs: # power of 2 search
  - 9 # 512 # min
  - 13 # 2048 # max
scale: # power of 2 search
  - 0 # min
  - 6 # max
mapping_size: # power of 2 search
  - 7 # min
  - 11 # max
lambda_discrete: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_gradient_time: #log search
  - 1.e-5 # min
  - 1.e+1 # max
lambda_tvn: #log search
  - 1.e-5 # min
  - 1.e+1 # max
act: [tanh, relu]
arch: [default, default-BN, Vlarge, skip-4, skip-5, skip-6]
verbose: 0
